model_name: SAGE
loader_type: MiniF
data_name: yelp

# preprocess params
norm_type: norm01
preprocess: None
n_bins: 32

# model params
d_hidden: 64

# dyple layer
use_dyple: True
dy_raw_bin_width: True
init_bin_width: False
d_feat_emb: 32

# pre mlp
pre_n_layers: 0  # [0,+inf]
pre_use_bn: True
pre_dropout: 0.1

# gnn
gnn_n_layers: 3  # [1,+inf]
gnn_dropout: 0.1
gnn_use_bn: True
gnn_use_res: True
gnn_agg: max_pool

# mha
use_mha: True
mha_n_layers: 1  # [1,+inf]
mha_n_heads: 4  # [1,+inf]
mha_alpha: 0.2

## post mlp
# post_n_layers: 1  # [1,+inf]
# post_use_bn: True
# post_dropout: 0.1

## pre sage
# use_presage: False

# dataloader params
bs: 128
val_bs: 1280 #11500

# optimization params
lr: 0.001
weight_decay: 0
max_epochs: 22222
patience: 31
device: cuda
device_id: 0
seed: 42
nowandb: True

