data_name: yelp
data_dir: ./data/
train_ratio: 0.2
test_ratio: 0.67
save_dir: ./pytorch_models/
model: PCGNN
multi_relation: GNN
emb_size: 64
thres: 0.5
rho: 0.4
seed: 2
optimizer: adam
lr: 0.01
weight_decay: 0.001
batch_size: 1024
num_epochs: 100
valid_epochs: 5
alpha: 2
no_cuda: false
cuda_id: '0'
split_path: ./shared/splits/yelpchi/yelpchi_tr20_split_seed2.npz
run_mode: unified_final_yelpchi_tr20_kaggle_t4_seed2_rho0p4
results_dir: ./results/unified-final/yelpchi/pcgnn/tr20/seed2
