alpha: 2
batch_size: 256
cuda_id: '0'
data_dir: ./data/
data_name: amazon
emb_size: 64
lr: 0.005
model: PCGNN
multi_relation: GNN
no_cuda: false
num_epochs: 51
optimizer: adam
rho: 0.5
save_dir: ./pytorch_models/
seed: 72
test_ratio: 0.67
thres: 0.4
train_ratio: 0.4
valid_epochs: 5
weight_decay: 0.0005
