/workspace/COMP8851-fraud-dataset-analysis/models/dga-gnn/dga_gnn_upstream/code
dname: amazon
project: dga_reproduction
model: dga
bin_encoding: true
n_head: 1
n_hidden: 128
p: 0.3
k: 4
z: 0.05
seed: 2
bs: 32
lr: 0.001
weight_decay: 0.0005
max_epochs: 2
patience: 25
usegpu: true
gpuid: 0
nowandb: true
