data_name: yelp
data_dir: ./data/
train_ratio: 0.4
test_ratio: 0.67
save_dir: ./pytorch_models/
model: PCGNN
multi_relation: GNN
emb_size: 64
thres: 0.5
rho: 0.4
seed: 72
optimizer: adam
lr: 0.01
weight_decay: 0.001
batch_size: 1024
num_epochs: 100
valid_epochs: 5
alpha: 2
no_cuda: false
cuda_id: '0'
split_path: ./shared/splits/yelpchi/yelpchi_tr40_split_seed2.npz
run_mode: unified_tuning_yelpchi_tr40_rho0p4_kaggle_t4_seed72
results_dir: ./results/unified/yelpchi/pcgnn/tuning_tr40/rho_0p4
