alpha: 2
batch_size: 256
cuda_id: '0'
data_dir: ./data/
data_name: amazon
emb_size: 64
lr: 0.005
model: PCGNN
multi_relation: GNN
no_cuda: false
num_epochs: 51
optimizer: adam
rho: 0.4
save_dir: ./pytorch_models/
seed: 72
test_ratio: 0.6666666666666666
thres: 0.4
train_ratio: 0.4
valid_epochs: 5
weight_decay: 0.0005
split_path: ./shared/splits/amazon/amazon_TR40_seed2.npz
run_mode: unified_tuning_amazon_tr40_rho0p4_seed72
results_dir: ./results/unified/amazon/pcgnn/tuning_tr40/rho_0p4
