data_name: yelp
data_dir: ./data/
train_ratio: 0.4
test_ratio: 0.67
save_dir: ./pytorch_models/
split_path: null
run_mode: smoke_test_kaggle_t4
results_dir: ./results/smoke-test-kaggle-t4
model: PCGNN
multi_relation: GNN
emb_size: 64
thres: 0.5
rho: 0.5
seed: 72
optimizer: adam
lr: 0.01
weight_decay: 0.001
batch_size: 1024
num_epochs: 2
valid_epochs: 1
alpha: 2
no_cuda: false
cuda_id: '0'
